### ISSUE TITLE
IsWord Error Response

### ISSUE THREAD

**Issue by KaiQ** [Tima-Is-My-Association/TIMA#10]
The [API.md](https://github.com/Tima-Is-My-Association/TIMA/blob/master/API.md#check-if-a-word-is-a-word-1) file says that you receive an 404 Error if the Word was not found... I received an 203 Error

... also there are 2 "Check if a word is a word" entries in this file ;-)

**Comment by jnphilipp** [comment]
Could you post the request.

**Comment by KaiQ** [comment]
Client -> Server
/api/words/isa/
word=ReallyNotAWord&language=DE

Server -> Client
HTTP Status Code: 203
HTTP Body: "Error downloading https://tima.jnphilipp.org/api/words/isa/ - server replied: NOT FOUND"

the API.md says there should be an 404 Status Code if TIMA dont know the word
